---
title: "Statistical tests"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Chi-square test of the aggression frequency between colonies nesting within and outside wood ant territory

```{r message = FALSE}
library(fusca.defence)
# Load data with the results of the aggression test - basic variant
data("aggression_probing_tests")
# For experiments with the use of 20 F. sanguinea ants introduced into arena around F. fusca nest
# T - within territory, B - beyond territory
# Colonies are classified according to the maximal number of aggressive ants exceeding
# threshold number
chi_sq_test(treatment_ = "sanguinea_20")

```


```{r}
# The same as above but for treatment with the use of a signle F. sanguinea ant
chi_sq_test(treatment_ = "sanguinea_1")

```

# Wilcoxon test to examine difference in duration of aggression displayed by agitated F. fusca ants toward alien ant

```{r message = FALSE}
# Load dataset
data("agitation_tests")
# summarize duration of aggressive behaviour over the experiment

agitation_tests_summary <- group_by(agitation_tests, colony, treatment) %>%
  summarise(aggression_duration=sum(aggression_duration)) %>% 
  left_join(distinct(select(agitation_tests, colony, territory)))

# difference in aggression toward F. polyctena between colonies located within and 
# outside rufa territory
x<-filter(agitation_tests_summary, treatment=="F. polyctena", territory=="B")$aggression_duration
y<-filter(agitation_tests_summary, treatment=="F. polyctena", territory=="T")$aggression_duration
cat(sprintf("Median time of aggression of colonies from within and from outside
wood ant territory: %f sec., %f sec., respectively", median(y), median(x)))
wilcox.test(x,y)

# difference in aggression toward F. sanguinea between colonies located within and 
# outside rufa territory
x<-filter(agitation_tests_summary, treatment=="F. sanguinea", territory=="B")$aggression_duration
y<-filter(agitation_tests_summary, treatment=="F. sanguinea", territory=="T")$aggression_duration
cat(sprintf("Median time of aggression of colonies from within and from outside
wood ant territory: %f sec., %f sec., respectively", median(y), median(x)))
wilcox.test(x,y)

# difference in aggression toward F. sanguinea and F. polyctena outside territory
sang_res <- filter(agitation_tests_summary, treatment=="F. sanguinea", territory=="B") %>%
  select(colony, aggression_duration)
polyctena_res <- filter(agitation_tests_summary, treatment=="F. polyctena", territory=="B") %>%
  select(colony, aggression_duration)
res <- left_join(sang_res, polyctena_res, by=c("colony"))
cat(sprintf("Median time of aggression toward F. polyctena and 
F. sanguinea: %f sec., %f sec., respectively", 
median(res$aggression_duration.y), 
median(res$aggression_duration.x)))
wilcox.test(res$aggression_duration.x, res$aggression_duration.y, paired=TRUE)
```
